# frozen_string_literal: true

module Rack
  module Cargo
    module ResponseBuilder
      class << self
        def call(request, state)
          app_response = state.fetch(:app_response)

          name = request.fetch("name", autogenerated_name)

          state[:response] = {
            RESPONSE_NAME => name,
            RESPONSE_STATUS => app_response.fetch(:status),
            RESPONSE_HEADERS => app_response.fetch(:headers),
            RESPONSE_BODY => JSON.parse(app_response.fetch(:body).join)
          }
        end

        def autogenerated_name
          "unnamed_#{SecureRandom.hex(6)}"
        end
      end
    end
  end
end
